apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: locker01/app:v1
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
