apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31041
  selector:
    app: app
